FROM amd64/node:16 as build

WORKDIR /app
COPY package.json .
RUN npm install

COPY public ./public
COPY src ./src
RUN npm run build

# Copy build artifacts into an nginx container

FROM amd64/nginx:1.21
COPY --from=build /app/build /usr/share/nginx/html
